# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: City Hall Wayfinding
email: digital@boston.gov
description: > # this means to ignore newlines until "baseurl:"
  A base for any static HTML projects
baseurl: ENV['BASE_URL'] # the subpath of your site, e.g. /blog
twitter_username: CityOfBoston
github_username:  CityOfBoston

# Build settings
markdown: kramdown

exclude: [node_modules, package.json, Gulpfile, Gemfile, Gemfile.lock, vendor, Rakefile, Procfile, config.ru]
keep_files: [assets]
permalink: '/:collection/:title/'

collections:
  floors:
    output: true
    permalink: /floor/:path.html

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: floors
    values:
      layout: "floor"

test:
  post:
    - rake test
